export const serviceOptions = [
  { value: 'Select', label: 'Select' },
  { value: 'Home removals', label: 'Home removals' },
  { value: 'Office removals', label: 'Office removals' },
  { value: 'Man and van', label: 'Man and van' },
  { value: 'Studio flat', label: 'Studio flat' },
  { value: '1 bed property', label: '1 bed property' },
  { value: '2-bed property', label: '2 bed property' },
  { value: '3-bed property', label: '3 bed property' },
  { value: '4-bed property', label: '4 bed property' },
  { value: 'Furniture & Appliances', label: 'Furniture & Appliances' },
  { value: 'Storage', label: 'Storage' },
  //   { value: 'slate', label: 'Slate', color: '#253858' },
  //   { value: 'silver', label: 'Silver', color: '#666666' },
];

export const citiesOptions = [
  { value: 'london', label: 'London' },
  { value: 'birmingham', label: 'Birmingham' },
  { value: 'manchester', label: 'Manchester' },
  { value: 'liverpool', label: 'Liverpool' },
  { value: 'bristol', label: 'Bristol' },
  { value: 'leeds', label: 'Leeds' },
  { value: 'newcastle', label: 'Newcastle' },
  { value: 'sheffield', label: 'Sheffield' },
  { value: 'nottingham', label: 'Nottingham' },
  { value: 'southampton', label: 'Southampton' },
  { value: 'norwich', label: 'Norwich' },
  { value: 'cardiff', label: 'Cardiff' },
  { value: 'cambridge', label: 'Cambridge' },
  { value: 'oxford', label: 'Oxford' },
  { value: 'brighton', label: 'Brighton' },
  { value: 'plymouth', label: 'Plymouth' },
  { value: 'portsmouth', label: 'Portsmouth' },
  { value: 'leicester', label: 'Leicester' },
  { value: 'coventry', label: 'Coventry' },
  { value: 'york', label: 'York' },
  { value: 'hull', label: 'Hull' },
  { value: 'bradford', label: 'Bradford' },
  { value: 'stoke-on-trent', label: 'Stoke-on-Trent' },
  { value: 'wolverhampton', label: 'Wolverhampton' },
  { value: 'derby', label: 'Derby' },
  { value: 'swansea', label: 'Swansea' },
  { value: 'southend-on-sea', label: 'Southend-on-Sea' },
  { value: 'sunderland', label: 'Sunderland' },
  { value: 'nottingham', label: 'Nottingham' },
  { value: 'luton', label: 'Luton' },
  { value: 'preston', label: 'Preston' },
  { value: 'blackpool', label: 'Blackpool' },
  { value: 'reading', label: 'Reading' },
  { value: 'northampton', label: 'Northampton' },
  { value: 'middlesbrough', label: 'Middlesbrough' },
  { value: 'peterborough', label: 'Peterborough' },
  { value: 'bournemouth', label: 'Bournemouth' },
  { value: 'stockport', label: 'Stockport' },
  { value: 'ipswich', label: 'Ipswich' },
  { value: 'sunderland', label: 'Sunderland' },
  { value: 'oxford', label: 'Oxford' },
  { value: 'bristol', label: 'Bristol' },
  { value: 'swindon', label: 'Swindon' },
  { value: 'huddersfield', label: 'Huddersfield' },
  { value: 'glasgow', label: 'Glasgow' },
  { value: 'edinburgh', label: 'Edinburgh' },
  { value: 'dundee', label: 'Dundee' },
];
