export const city = [
  {
    name: "East London",
    id: "eastLondon",
    status: false,
    subs: [
      "Acle",
      "Aldeburgh",
      "Ampthill",
      "Arlesey",
      "Attleborough",
      "Aylsham",
      "Baldock",
      "Barton-le-Clay",
      "Basildon",
      "Bedford",
      "Beccles",
      "Berkhamsted",
      "Biggleswade",
      "Billericay",
      "Bishop’s Stortford",
      "Borehamwood",
      "Brandon",
      "Braintree",
      "Brentwood",
      "Brightlingsea",
      "Bungay",
      "Buntingford",
      "Burnham-on-Crouch",
      "Bury St. Edmunds",
      "Bushey",
      "Cambridge",
      "Cambridgeshire",
      "Canvey Island",
      "Carlton Colville",
      "Chatteris",
      "Chelmsford",
      "Cheshunt",
      "Chigwell",
      "Chipping Ongar",
      "Chorleywood",
      "Clacton on Sea",
      "Clare",
      "Coggeshall",
      "Corringham",
      "Cranfield",
      "Cromer",
      "Dereham",
      "Diss",
      "Downham Market",
      "Dunstable",
      "Ely",
      "Epping",
      "Eye",
      "Fakenham",
      "Felixstowe",
      "Flitwick",
      "Foxley",
      "Framlingham",
      "Frinton-on-Sea",
      "Gorleston on Sea",
      "Hackney",
      "Godmanchester",
      "Great Dunmow",
      "Grays",
      "Great Yarmouth",
      "Hadleigh",
      "Halesworth",
      "Halstead",
      "Harleston",
      "Harlow",
      "Harpenden",
      "Harwich",
      "Hatfield",
      "Haverhill",
      "Hemel Hempstead",
      "Hertford",
      "Hertfordshire",
      "Hingham",
      "Hitchin",
      "Hoddesdon",
      "Holt",
      "Houghton Regis",
      "Hunstanton",
      "Huntingdon",
      "Ipswich",
      "Kempston",
      "Kesgrave",
      "Kings Lynn",
      "Leighton Buzzard",
      "Leigh-on-Sea",
      "Leiston",
      "Letchworth",
      "Linslade",
      "Loddon",
      "Loughton",
      "Lowestoft",
      "Luton",
      "Maldon",
      "Manningtree",
      "March",
      "Marston Moretaine",
      "Mildenhall",
      "Needham Market",
      "Newmarket",
      "Norfolk",
      "North Walsham",
      "Norwich",
      "Orford",
      "Peterborough",
      "Potter’s Bar",
      "Ramsey",
      "Rayleigh",
      "Reepham",
      "Rickmansworth",
      "Rochford",
      "Royston",
      "Saffron Walden",
      "Sandy",
      "Sawbridgeworth",
      "Saxmundham",
      "Shefford",
      "Sheringham",
      "Soham",
      "South Ockendon",
      "South Woodham Ferrers",
      "Southend",
      "Southminster",
      "Southwold",
      "Sprowston",
      "St. Alban’s",
      "St. Neots",
      "Stalham",
      "Stanford Le Hope",
      "Stevenage",
      "Stotfold",
      "Stowmarket",
      "Sudbury",
      "Suffolk",
      "Swaffham",
      "Thaxted",
      "Thetford",
      "Thorpe St Andrew",
      "Thurrock",
      "Tring",
      "Waltham Abbey",
      "Waltham Cross",
      "Walton-on-the-Naze",
      "Watton",
      "Ware",
      "Watford",
      "Wells-next-the-Sea",
      "Welwyn Garden City",
      "West Mersea",
      "West Tilbury",
      "Whittlesey",
      "Wickford",
      "Wisbech",
      "Witham",
      "Wivenhoe",
      "Woburn",
      "Woodbridge",
    ],
  },
  {
    name: "Central England",
    id: "centralEngland",
    status: false,
    subs: ["Aylesbury"],
  },
  {
    name: "Central London",
    id: "centralLondon",
    status: false,
    subs: ["Belgravia", "Canary Wharf", "Covent Garden", "Southwark"],
  },
  {
    name: "East England",
    id: "eastEngland",
    status: false,
    subs: [
      "Acle",
      "Aldeburgh",
      "Ampthill",
      "Arlesey",
      "Attleborough",
      "Aylsham",
      "Baldock",
      "Barton-le-Clay",
      "Basildon",
      "Bedford",
      "Beccles",
      "Berkhamsted",
      "Biggleswade",
      "Billericay",
      "Bishop’s Stortford",
      "Borehamwood",
      "Brandon",
      "Braintree",
      "Brentwood",
      "Brightlingsea",
      "Bungay",
      "Buntingford",
      "Burnham-on-Crouch",
      "Bury St. Edmunds",
      "Bushey",
      "Cambridge",
      "Cambridgeshire",
      "Canvey Island",
      "Carlton Colville",
      "Chatteris",
      "Chelmsford",
      "Cheshunt",
      "Chigwell",
      "Chipping Ongar",
      "Chorleywood",
      "Clacton on Sea",
      "Clare",
      "Coggeshall",
      "Corringham",
      "Cranfield",
      "Cromer",
      "Dereham",
      "Diss",
      "Downham Market",
      "Dunstable",
      "Ely",
      "Epping",
      "Eye",
      "Fakenham",
      "Felixstowe",
      "Flitwick",
      "Foxley",
      "Framlingham",
      "Frinton-on-Sea",
      "Gorleston on Sea",
      "Hackney",
      "Godmanchester",
      "Great Dunmow",
      "Grays",
      "Great Yarmouth",
      "Hadleigh",
      "Halesworth",
      "Halstead",
      "Harleston",
      "Harlow",
      "Harpenden",
      "Harwich",
      "Hatfield",
      "Haverhill",
      "Hemel Hempstead",
      "Hertford",
      "Hertfordshire",
      "Hingham",
      "Hitchin",
      "Hoddesdon",
      "Holt",
      "Houghton Regis",
      "Hunstanton",
      "Huntingdon",
      "Ipswich",
      "Kempston",
      "Kesgrave",
      "Kings Lynn",
      "Leighton Buzzard",
      "Leigh-on-Sea",
      "Leiston",
      "Letchworth",
      "Linslade",
      "Loddon",
      "Loughton",
      "Lowestoft",
      "Luton",
      "Maldon",
      "Manningtree",
      "March",
      "Marston Moretaine",
      "Mildenhall",
      "Needham Market",
      "Newmarket",
      "Norfolk",
      "North Walsham",
      "Norwich",
      "Orford",
      "Peterborough",
      "Potter’s Bar",
      "Ramsey",
      "Rayleigh",
      "Reepham",
      "Rickmansworth",
      "Rochford",
      "Royston",
      "Saffron Walden",
      "Sandy",
      "Sawbridgeworth",
      "Saxmundham",
      "Shefford",
      "Sheringham",
      "Soham",
      "South Ockendon",
      "South Woodham Ferrers",
      "Southend",
      "Southminster",
      "Southwold",
      "Sprowston",
      "St. Alban’s",
      "St. Neots",
      "Stalham",
      "Stanford Le Hope",
      "Stevenage",
      "Stotfold",
      "Stowmarket",
      "Sudbury",
      "Suffolk",
      "Swaffham",
      "Thaxted",
      "Thetford",
      "Thorpe St Andrew",
      "Thurrock",
      "Tring",
      "Waltham Abbey",
      "Waltham Cross",
      "Walton-on-the-Naze",
      "Watton",
      "Ware",
      "Watford",
      "Wells-next-the-Sea",
      "Welwyn Garden City",
      "West Mersea",
      "West Tilbury",
      "Whittlesey",
      "Wickford",
      "Wisbech",
      "Witham",
      "Wivenhoe",
      "Woburn",
      "Woodbridge",
    ],
  },
  {
    name: "East Midlands England",
    id: "eastMidlandsEngland",
    status: false,
    subs: [
      "Alford",
      "Alfreton",
      "Arnold",
      "Ashbourne",
      "Ashby-de-la-Zouch",
      "Bakewell",
      "Batley",
      "Beeston Broxtowe",
      "Belper",
      "Bingham",
      "Bolsover",
      "Boston",
      "Bottesford",
      "Bourne",
      "Brackley",
      "Braunstone",
      "Bulwell",
      "Burgh-le-Marsh",
      "Burton Latimer",
      "Buxton",
      "Caistor",
      "Carlton",
      "Chapel-en-le-Frith",
      "Chesterfield",
      "Clay Cross",
      "Coalville",
      "Corby",
      "Cotgrave",
      "Crowland",
      "Darley Dale",
      "Daventry",
      "Derby",
      "Derbyshire",
      "Desborough",
      "Dronfield",
      "Earl Shilton",
      "Eastwood",
      "Gainsborough",
      "Glossop",
      "Grantham",
      "Heanor",
      "Harworth",
      "Higham Ferrers",
      "Hinckley",
      "Holbeach",
      "Horncastle",
      "Hucknall",
      "Ilkeston",
      "Irthlingborough",
      "Kettering",
      "Kimberley",
      "Kirkby in Ashfield",
      "Leicester",
      "Leicestershire",
      "Lincoln",
      "Lincolnshire",
      "Long Eaton",
      "Long Sutton",
      "Loughborough",
      "Louth",
      "Lutterworth",
      "Mablethorpe",
      "Man’s field",
      "Man’s field Woodhouse",
      "Market Bosworth",
      "Market Deeping",
      "Market Harborough",
      "Market Rasen",
      "Melton Mowbray",
      "Newark on Trent",
      "New Mills",
      "Northampton",
      "Northamptonshire",
      "North Hykeham",
      "Nottingham",
      "Nottinghamshire",
      "Oakham",
      "Ollerton",
      "Oundle",
      "Raunds",
      "Retford",
      "Ripley",
      "Rothwell",
      "Rushden",
      "Rutland",
      "Sandiacre",
      "Shepshed",
      "Shirebrook",
      "Skegness",
      "Sleaford",
      "Southwell",
      "Spalding",
      "Spilsby",
      "Stamford",
      "Stapleford",
      "Sutton-in-Ashfield",
      "Swadlincote",
      "Syston",
      "Towcester",
      "Uppingham",
      "Wainfleet All Saints",
      "Wellingborough",
      "West Bridgford",
      "Whaley Bridge",
      "Wigston",
      "Wirksworth",
      "Worksop",
      "Wragby",
    ],
  },
];
